name: Generate and Deploy to Github Pages
# touchme
on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build:prod

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        # Filter on branch
        if: github.ref == 'refs/heads/master'
        with:
          folder: dist # The folder the action should deploy.
